name: Build Impeller SDK

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        id: setup-msys2

      - uses: kekekeks/setup-windows10-sdk-action@install-all-features-1
        with:
          sdk-version: 22621
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run build
        shell: pwsh
        run: ./build.ps1

      - name: Debug build
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          msys2-location: ${{ steps.setup-msys2.outputs.msys2-location }}


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: impeller-sdk-windows-x64
          path: flutter/engine/src/out/*/zip_archives/**/*.zip
          if-no-files-found: warn
