name: Build Impeller SDK

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:

      - name: Check disk space
        run: df . -h
      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true
          echo "some directories deleted"
      - name: Check disk space
        run: |
          df . -h
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl python3 python3-pip wget unzip ninja-build \
            build-essential libglib2.0-dev pkg-config clang cmake xz-utils
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Run build
        run: bash ./build.sh

      - name: Check disk space
        run: df . -h
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: impeller-sdk-linux-x64
          path: flutter/engine/src/out/*/zip_archives/**/*.zip
          if-no-files-found: warn

  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Run build
        run: bash ./build.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: impeller-sdk-macos-arm64
          path: flutter/engine/src/out/*/zip_archives/**/*.zip
          if-no-files-found: warn
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: kekekeks/setup-windows10-sdk-action@install-all-features-1
        with:
          sdk-version: 22621
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run build
        shell: pwsh
        run: ./build.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: impeller-sdk-windows-x64
          path: flutter/engine/src/out/*/zip_archives/**/*.zip
          if-no-files-found: warn

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-ubuntu, build-windows]
    if: github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Generate release id
        run: ./genrelease.sh 
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_ID }}
          name: ${{ env.RELEASE_ID }}
          draft: false
          body_path: ./release.txt
          prerelease: false
          files: files/*
